// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/4f7524fc65c0d1389af81a83a95dfe1ea59ad5e9/electron/electron-prebuilt.d.ts
declare module 'electron-prebuilt' {
	var electron: string;
	export = electron;
}
